<?php
/**
 * @copyright  Copyright (c) 2016, Net Inventors GmbH
 * @category   Shopware
 * @author     hrombach
 */

namespace NetiPhpExcel;

use Shopware\Components\Plugin;
use Symfony\Component\DependencyInjection\ContainerBuilder;

class NetiPhpExcel extends Plugin
{
    public function build(ContainerBuilder $container)
    {
        if (! class_exists('PHPExcel')) {
            require_once 'vendor/autoload.php';
        }

        parent::build($container); // TODO: Change the autogenerated stub
    }
}